# Configurações do GitHub para salvar dados
# Você precisa configurar essas variáveis no Streamlit Cloud

# Token do GitHub (crie em: https://github.com/settings/tokens)
# Permissões necessárias: repo (acesso completo ao repositório)
GITHUB_TOKEN = ""

# Informações do repositório
GITHUB_REPO_OWNER = "U235107"
GITHUB_REPO_NAME = "Streamlit_dash"
